# 1  What is the total revenu generated by male vs female customers?

select gender, sum(purchase_amount) as revenue
from customer_behavior
group by gender;

# 2 Which customers used a discount but still spent more than the avrg purchase amount ?
select customer_id, purchase_amount
from customer_behavior
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer_behavior);

# 3 Which of the top 5 products with highest avg review rating ?

select item_purchased, round(avg(review_rating), 2) as "Average Product Rating"
from customer_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;

	
-- 4 compare the avg purchase amounts between the standard and express shipping ?
select shipping_type,
round(avg(purchase_amount),2) 
from customer_behavior
where shipping_type in ('standard','express')
group by shipping_type;


-- Q5. do subscribed customers spend more? copare average spend and total revenue 
-- between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_behavior
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6  Which 5 products have the highest percentage of purchases with discounts applied ?
select item_purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end)/ count(*) * 100,2) as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;
 
-- Q7 segment customers into new, returning,and loyal based on their 
-- toal no.of previous perchases, and show the count of each segment?

with customer_type as(
select customer_id,previous_purchases,
case 
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal'
     end as customer_segment
     from customer_behavior
     )
     select customer_segment, count(*) as 'Number of customers'
     from customer_type
     group by customer_segment;
     
-- Q8. What are the top 3 most purchased products within each category ?


with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER () over(partition by category order by count(customer_id) desc) as item_rank
from customer_behavior
group by category, item_purchased

)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9  Are customers are repeat byers ( more thane 5 previous purchases also likely to subscribe ?

select subscription_status,
count(customer_id) as repeat_buyers
from customer_behavior
where previous_purchases >5
group by subscription_status;

-- Q 10 What is the revenue contribution of each age group

select age_group,
sum(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;







